export const ActionTypes = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_PROFILE_PICTURE: 'UPDATE_PROFILE_PICTURE',
    SIGNUP: 'SIGNUP'

    // SET_PRODUCTS: "SET_PRODUCTS",
    // SELECTED_PRODUCT: "SELECTED_PRODUCT",
    // REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT"
}